# Generated by Django 5.0.1 on 2025-03-19 04:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=300, primary_key=True, serialize=False, unique=True)),
                ('regionName', models.CharField(max_length=155)),
                ('regionCode', models.CharField(max_length=20)),
                ('countyName', models.CharField(max_length=155)),
                ('countyCode', models.CharField(max_length=20)),
                ('streetName', models.CharField(max_length=255)),
                ('streetNumber', models.CharField(max_length=20)),
                ('postalCode', models.CharField(max_length=30)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('phoneNumber', models.CharField(max_length=20)),
                ('comment', models.TextField(blank=True, max_length=355, null=True)),
                ('isDefault', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
