services:
  ecw-backend:
    container_name: ecw-backend
    build:
      context: ./server
    image: hellocodefusion/ecw-backend:pv3
    command: >
      sh -c "
        python manage.py collectstatic --no-input &&
        python manage.py makemigrations &&
        python manage.py migrate &&
        python build.py &&
        uvicorn core.asgi:application --host 0.0.0.0 --port 8000
      "
    ports:
      - 8000:8000
    working_dir: /server
    environment:
      PYTHONUNBUFFERED: 1
    env_file:
      - /server/core/.env
    restart: always
    networks:
      - ecw-red
  ecw-frontend:
    container_name: ecw-frontend
    build:
      context: ./client
      args:
        NEXT_PUBLIC_API_KEY_FIREBASE: ${NEXT_PUBLIC_API_KEY_FIREBASE}
        NEXT_PUBLIC_AUTH_DOMAIN_FIREBASE: ${NEXT_PUBLIC_AUTH_DOMAIN_FIREBASE}
        NEXT_PUBLIC_PROJECT_ID_FIREBASE: ${NEXT_PUBLIC_PROJECT_ID_FIREBASE}
        NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET_FIREBASE: ${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET_FIREBASE}
        NEXT_PUBLIC_SENDER_ID_FIREBASE: ${NEXT_PUBLIC_SENDER_ID_FIREBASE}
        NEXT_PUBLIC_APP_ID_FIREBASE: ${NEXT_PUBLIC_APP_ID_FIREBASE}
        NEXT_PUBLIC_MEASUREMENT_ID_FIREBASE: ${NEXT_PUBLIC_MEASUREMENT_ID_FIREBASE}
        NEXT_PUBLIC_URL_DOCKER: ${NEXT_PUBLIC_URL_DOCKER}
        NEXT_PUBLIC_URL_PRO: ${NEXT_PUBLIC_URL_PRO}
        NEXT_PUBLIC_AWS_S3_CUSTOM_DOMAIN: ${NEXT_PUBLIC_AWS_S3_CUSTOM_DOMAIN}   
        NEXT_PUBLIC_GOOGLE_MAPS: ${NEXT_PUBLIC_GOOGLE_MAPS}
        NEXT_PUBLIC_MAP_ID: ${NEXT_PUBLIC_MAP_ID}

    image: hellocodefusion/ecw-frontend:pv3
    command: npx next start -H 0.0.0.0 -p 3000 
    ports:
      - 3000:3000
    working_dir: /client
    environment:
      NODE_ENV: production
    env_file:
      - /client/.env.local
    restart: always
    networks:
      - ecw-red
  ecw-nginx:
    container_name: ecw-nginx
    build:
      context: ./nginx
    image: hellocodefusion/ecw-nginx:pv4
    ports:
      - 80
    depends_on:
      - ecw-backend
      - ecw-frontend
      - nginx-proxy
      - letsencrypt
    environment:
      - VIRTUAL_HOST=ecommerce-demo.codefusion.cl
      - LETSENCRYPT_HOST=ecommerce-demo.codefusion.cl
    restart: always
    networks:
      - ecw-red
  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhostd.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy 
    networks:
      - ecw-red
  letsencrypt:
    container_name: letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion 
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:z
      - vhostd:/etc/nginx/vhostd.d
      - html:/usr/share/nginx/html
    networks:
      - ecw-red
volumes:
  certs:
  html:
  vhostd:
networks:
  ecw-red:
    driver: bridge
