# Generated by Django 5.0.1 on 2025-03-19 04:26

import apps.blog.models
import django.db.models.deletion
import tinymce.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=300, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=155, unique=True)),
                ('slug', models.SlugField(max_length=155, unique=True)),
                ('icon', models.ImageField(blank=True, default=None, null=True, upload_to=apps.blog.models.blog_category_thumbnail_directory)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('views', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'Blog category',
                'verbose_name_plural': 'Blog categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=300, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('not_active', 'not_active'), ('active', 'active')], default='active', max_length=255)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('thumbnail', models.ImageField(blank=True, default=None, null=True, upload_to=apps.blog.models.blog_post_thumbnail_directory)),
                ('title', models.CharField(max_length=200)),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
                ('stars', models.FloatField(default=0)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=300, primary_key=True, serialize=False, unique=True)),
                ('comment', models.TextField(max_length=500)),
                ('stars', models.IntegerField(choices=[(1, '1 estrella'), (4, '4 estrellas'), (2, '2 estrellas'), (5, '5 estrellas'), (3, '3 estrellas')], default=1)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BlogCategoryViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
                ('blog_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_category_view_count', to='blog.blogcategory')),
            ],
        ),
    ]
