# Generated by Django 5.0.1 on 2025-07-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='stars',
            field=models.IntegerField(choices=[(4, '4 estrellas'), (2, '2 estrellas'), (5, '5 estrellas'), (1, '1 estrella'), (3, '3 estrellas')], default=1),
        ),
    ]
