# Generated by Django 4.2 on 2026-04-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_postcomment_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='stars',
            field=models.IntegerField(choices=[(1, '1 estrella'), (2, '2 estrellas'), (3, '3 estrellas'), (4, '4 estrellas'), (5, '5 estrellas')], default=1),
        ),
    ]
