# Generated by Django 5.0.1 on 2025-03-19 04:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=300, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=155, unique=True)),
                ('discount_percent', models.FloatField(blank=True, null=True)),
                ('discount_value', models.FloatField(blank=True, null=True)),
                ('discount_type', models.CharField(choices=[('value', 'value'), ('percent', 'percent')], default='value', max_length=155)),
                ('limit', models.IntegerField(default=150)),
                ('discount_expire', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=300, primary_key=True, serialize=False, unique=True)),
                ('isUsed', models.BooleanField(default=False)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupons.coupon')),
            ],
        ),
    ]
