# Generated by Django 5.0.1 on 2025-07-27 14:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercoupon',
            name='isUsed',
        ),
        migrations.RemoveField(
            model_name='usercoupon',
            name='purchase',
        ),
        migrations.AddField(
            model_name='usercoupon',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercoupon',
            name='status',
            field=models.CharField(choices=[('is_applied', 'Applied'), ('is_used', 'Used'), ('is_claimed', 'Claimed'), ('is_expired', 'Expired')], default='is_claimed', max_length=30),
        ),
        migrations.AlterField(
            model_name='usercoupon',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons', to=settings.AUTH_USER_MODEL),
        ),
    ]
