# Generated by Django 5.0.1 on 2025-07-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_remove_usercoupon_isused_remove_usercoupon_purchase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'percent'), ('free_delivery', 'free_delivery'), ('value', 'value')], default='value', max_length=155),
        ),
        migrations.AlterField(
            model_name='usercoupon',
            name='status',
            field=models.CharField(choices=[('is_claimed', 'Claimed'), ('is_used', 'Used'), ('is_applied', 'Applied'), ('is_expired', 'Expired')], default='is_claimed', max_length=30),
        ),
    ]
