# Generated by Django 5.0.1 on 2025-07-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_alter_coupon_discount_type_alter_usercoupon_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'percent'), ('value', 'value'), ('free_delivery', 'free_delivery')], default='value', max_length=155),
        ),
        migrations.AlterField(
            model_name='usercoupon',
            name='status',
            field=models.CharField(choices=[('is_used', 'Used'), ('is_applied', 'Applied'), ('is_claimed', 'Claimed'), ('is_expired', 'Expired')], default='is_claimed', max_length=30),
        ),
    ]
