# Generated by Django 4.2 on 2026-04-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0006_alter_coupon_discount_type_alter_usercoupon_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'percent'), ('value', 'value'), ('free_delivery', 'free_delivery')], default='value', max_length=155),
        ),
    ]
