# Generated by Django 4.2 on 2026-04-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0007_alter_coupon_discount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('value', 'value'), ('free_delivery', 'free_delivery'), ('percent', 'percent')], default='value', max_length=155),
        ),
        migrations.AlterField(
            model_name='usercoupon',
            name='status',
            field=models.CharField(choices=[('is_expired', 'Expired'), ('is_applied', 'Applied'), ('is_used', 'Used'), ('is_claimed', 'Claimed')], default='is_claimed', max_length=30),
        ),
    ]
