# Generated by Django 4.2 on 2026-04-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0008_alter_coupon_discount_type_alter_usercoupon_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'percent'), ('value', 'value'), ('free_delivery', 'free_delivery')], default='value', max_length=155),
        ),
        migrations.AlterField(
            model_name='usercoupon',
            name='status',
            field=models.CharField(choices=[('is_applied', 'Applied'), ('is_claimed', 'Claimed'), ('is_expired', 'Expired'), ('is_used', 'Used')], default='is_claimed', max_length=30),
        ),
    ]
