# Generated by Django 4.2 on 2026-04-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0009_alter_coupon_discount_type_alter_usercoupon_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoupon',
            name='status',
            field=models.CharField(choices=[('is_used', 'Used'), ('is_applied', 'Applied'), ('is_claimed', 'Claimed'), ('is_expired', 'Expired')], default='is_claimed', max_length=30),
        ),
    ]
