# Generated by Django 5.0.1 on 2025-07-26 07:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=uuid.UUID('de5321e3-8515-4af1-9753-51b08301721b'), editable=False, max_length=300, primary_key=True, serialize=False, unique=True),
        ),
    ]
