# Generated by Django 5.0.1 on 2025-07-27 14:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAuth', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=uuid.UUID('45001a7c-1b02-4a4e-b754-8d31027fdf5e'), editable=False, max_length=300, primary_key=True, serialize=False, unique=True),
        ),
    ]
