# Generated by Django 5.0.1 on 2025-07-29 17:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAuth', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=uuid.UUID('d3de3ed7-e036-4d51-891b-3531fc8eb56c'), editable=False, max_length=300, primary_key=True, serialize=False, unique=True),
        ),
    ]
