# Generated by Django 5.0.1 on 2025-07-29 18:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAuth', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=uuid.UUID('3c241c78-9b97-431d-a1c9-a079541080a1'), editable=False, max_length=300, primary_key=True, serialize=False, unique=True),
        ),
    ]
