# Generated by Django 4.2 on 2026-04-16 06:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myAuth', '0005_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=uuid.UUID('10d2c4d1-b1c2-4eab-964d-f705f0880d23'), editable=False, max_length=300, primary_key=True, serialize=False, unique=True),
        ),
    ]
