# Generated by Django 4.2 on 2026-04-16 06:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myAuth', '0006_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=uuid.UUID('238e2794-093a-4704-8aac-4e74fd8ae9f2'), editable=False, max_length=300, primary_key=True, serialize=False, unique=True),
        ),
    ]
