# Generated by Django 5.0.1 on 2025-03-19 04:26

import apps.shop.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=300, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('icon', models.ImageField(blank=True, default=None, null=True, upload_to=apps.shop.models.category_icons_directory)),
                ('views', models.IntegerField(blank=True, default=0)),
                ('type', models.CharField(choices=[('brand', 'brand'), ('category', 'category'), ('special', 'special')], default='category', max_length=100)),
                ('subcategories', models.ManyToManyField(blank=True, to='shop.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='CategoryViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_view_count', to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=300, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(upload_to=apps.shop.models.product_image_directory)),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=3000, null=True)),
                ('stock', models.IntegerField()),
                ('status', models.CharField(choices=[('not_on_sale', 'not_on_sale'), ('on_sale', 'on_sale')], default='on_sale', max_length=255)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(blank=True, default=0)),
                ('stars', models.FloatField(default=0)),
                ('categories', models.ManyToManyField(blank=True, to='shop.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=300, primary_key=True, serialize=False, unique=True)),
                ('comment', models.TextField(max_length=500)),
                ('stars', models.IntegerField(choices=[(1, '1 estrella'), (4, '4 estrellas'), (2, '2 estrellas'), (5, '5 estrellas'), (3, '3 estrellas')], default=1)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productsComments', to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDimensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('length', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productsDimensions', to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.CharField(max_length=155)),
                ('value', models.CharField(max_length=155)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productsFeatures', to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=1000, upload_to=apps.shop.models.product_image_directory)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productsImages', to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productsViews', to='shop.product')),
            ],
        ),
    ]
