# Generated by Django 5.0.1 on 2025-07-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_productcomment_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='stars',
            field=models.IntegerField(choices=[(1, '1 estrella'), (3, '3 estrellas'), (2, '2 estrellas'), (5, '5 estrellas'), (4, '4 estrellas')], default=1),
        ),
    ]
