# Generated by Django 4.2 on 2026-04-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_productcomment_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='stars',
            field=models.IntegerField(choices=[(5, '5 estrellas'), (1, '1 estrella'), (3, '3 estrellas'), (4, '4 estrellas'), (2, '2 estrellas')], default=1),
        ),
    ]
