# Generated by Django 3.2 on 2026-06-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_productcomment_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='_shop_category_subcategories_+', to='shop.Category'),
        ),
    ]
