# Generated by Django 5.0.1 on 2025-03-19 04:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=300, primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=155)),
                ('name', models.CharField(max_length=155)),
                ('message', models.TextField(max_length=1200)),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=300, primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=155)),
            ],
            options={
                'verbose_name': 'newsletter',
                'verbose_name_plural': 'newsletters',
            },
        ),
    ]
