# Generated by Django 5.0.1 on 2025-03-19 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('null', 'null'), ('flow', 'flow'), ('mercadopago', 'mercadopago')], default='null', max_length=100)),
                ('media', models.CharField(max_length=100)),
                ('payerEmail', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=20)),
                ('amount', models.FloatField(default=0)),
                ('fee', models.FloatField(default=0)),
                ('taxes', models.FloatField(default=0)),
                ('received', models.FloatField(default=0)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.purchase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
