# Generated by Django 5.0.1 on 2025-03-19 04:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=300, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=150)),
                ('discount', models.IntegerField(default=0)),
                ('subtotal', models.IntegerField(default=0)),
                ('deliveryCost', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('bnbTotal', models.FloatField(blank=True, null=True)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('created', 'creada'), ('payed', 'pagada'), ('uncompleted', 'incompleta'), ('delivered', 'entregada')], default='created', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseDelivery',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=300, primary_key=True, serialize=False, unique=True)),
                ('shipmentNumber', models.IntegerField(blank=True, default=0, null=True)),
                ('region', models.CharField(max_length=255)),
                ('commune', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('streetNumber', models.CharField(max_length=255)),
                ('courier', models.CharField(default='CHILEXPRESS', max_length=100)),
                ('courierType', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('created', 'creada'), ('receivedForCourier', 'recibidaPorCourier'), ('inRoute', 'enRuta'), ('delivered', 'Entregado')], default='created', max_length=100)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=300, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.purchase')),
            ],
        ),
    ]
