# Generated by Django 5.0.1 on 2025-07-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('created', 'creada'), ('delivered', 'entregada'), ('payed', 'pagada'), ('uncompleted', 'incompleta')], default='created', max_length=100),
        ),
    ]
