# Generated by Django 5.0.1 on 2025-07-27 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_remove_usercoupon_isused_remove_usercoupon_purchase_and_more'),
        ('purchase', '0002_alter_purchase_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='coupon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_applied', to='coupons.usercoupon'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('uncompleted', 'incompleta'), ('created', 'creada'), ('payed', 'pagada'), ('delivered', 'entregada')], default='created', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_purchase', to=settings.AUTH_USER_MODEL),
        ),
    ]
