# Generated by Django 5.0.1 on 2025-07-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_purchase_coupon_alter_purchase_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('payed', 'pagada'), ('created', 'creada'), ('uncompleted', 'incompleta'), ('delivered', 'entregada')], default='created', max_length=100),
        ),
    ]
