# Generated by Django 5.0.1 on 2025-07-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_alter_purchase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('created', 'creada'), ('uncompleted', 'incompleta'), ('delivered', 'entregada'), ('payed', 'pagada')], default='created', max_length=100),
        ),
    ]
