# Generated by Django 4.2 on 2026-04-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_alter_purchase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('payed', 'pagada'), ('created', 'creada'), ('uncompleted', 'incompleta'), ('delivered', 'entregada')], default='created', max_length=100),
        ),
    ]
