# Generated by Django 4.2 on 2026-04-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_alter_purchase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('uncompleted', 'incompleta'), ('delivered', 'entregada'), ('created', 'creada'), ('payed', 'pagada')], default='created', max_length=100),
        ),
    ]
