# Generated by Django 4.2 on 2026-04-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_alter_purchase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('delivered', 'entregada'), ('uncompleted', 'incompleta'), ('payed', 'pagada'), ('created', 'creada')], default='created', max_length=100),
        ),
    ]
