# Generated by Django 5.0.1 on 2025-03-19 04:26

import apps.home.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=300, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('not_selected', 'not_selected'), ('selected', 'selected')], max_length=255)),
                ('thumbnail', models.ImageField(upload_to=apps.home.models.banner_directory)),
                ('alt', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
            },
        ),
    ]
